version: '3.8'

services:
  # 开发环境应用服务
  app-dev:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    env_file:
      - .env.dev
    environment:
      - PYTHONPATH=/app/src
      - ENVIRONMENT=development
    depends_on:
      - redis
    volumes:
      # 开发时挂载源代码目录，支持热重载
      - ./src:/app/src
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - userproxy-dev-network
    command: ["poetry", "run", "userproxy-dev"]

  # 本地Redis服务（仅开发环境）
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_dev_data:/data
    restart: unless-stopped
    networks:
      - userproxy-dev-network
    command: redis-server --appendonly yes

volumes:
  redis_dev_data:

networks:
  userproxy-dev-network:
    driver: bridge 