version: '3.8'

services:
  # 主应用服务
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=redis://redis:6379
      - PYTHONPATH=/app/src
    depends_on:
      - redis
    volumes:
      # 开发时可以挂载源代码目录
      # - ./src:/app/src
      # 挂载日志目录
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - userproxy-network

  # Redis服务
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - userproxy-network
    command: redis-server --appendonly yes

  # 开发环境服务（可选）
  app-dev:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    environment:
      - REDIS_URL=redis://redis:6379
      - PYTHONPATH=/app/src
      - ENVIRONMENT=development
    depends_on:
      - redis
    volumes:
      # 开发时挂载源代码目录
      - ./src:/app/src
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - userproxy-network
    command: ["poetry", "run", "userproxy-dev"]
    profiles:
      - dev

volumes:
  redis_data:

networks:
  userproxy-network:
    driver: bridge 