version: 1
formatters:
  simple:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  access:
    format: "%(asctime)s - %(message)s"
  error:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(filename)s:%(lineno)d - %(message)s"
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout
  access_file:
    class: logging.FileHandler
    level: INFO
    formatter: access
    filename: ./logs/saccess.log
  error_file:
    class: logging.FileHandler
    level: WARNING
    formatter: error
    filename: ./logs/error.log
loggers:
  access:
    level: INFO
    handlers: [access_file]
    propagate: False
root:
  level: INFO
  handlers: [console, error_file] 